/**
 * VIRGIL — Connector Registry
 *
 * Single source of truth for every external API integration.
 * Each entry declares the env vars required, the category, the display name,
 * and whether the key is currently configured.
 *
 * This registry drives:
 *   - The settings/keys status page (✅ / ❌ / ⚠️)
 *   - Runtime guard checks before connector calls
 *   - Future connector health-check pings
 */

export type ConnectorStatus = "configured" | "missing" | "untested";
export type ConnectorCategory =
  | "critical"
  | "llm"
  | "voice"
  | "calendar_email"
  | "communication"
  | "payments_finance"
  | "storage"
  | "search"
  | "code_dev"
  | "crm_business"
  | "maps_travel"
  | "real_estate"
  | "trading_finance"
  | "monitoring_security"
  // Real-World Command Layer
  | "food_delivery"
  | "brazil_ops"
  | "concierge"
  | "shopping_procurement"
  | "automotive"
  | "private_aviation"
  | "hotels_events"
  | "news_intelligence"
  | "safety_location"
  | "medical_pharmacy"
  | "brazil_business"
  | "dev_infra";

export interface ConnectorDef {
  id: string;
  name: string;
  category: ConnectorCategory;
  envVars: string[];
  description: string;
  docsUrl?: string;
  /** True when all envVars are non-empty in process.env. */
  configured: boolean;
}

function allSet(keys: string[]): boolean {
  return keys.every((k) => !!process.env[k]);
}

export const CONNECTOR_REGISTRY: ConnectorDef[] = [
  // ── CRITICAL ─────────────────────────────────────────────────────────────
  {
    id: "supabase_db",
    name: "Supabase (Database)",
    category: "critical",
    envVars: ["DATABASE_URL"],
    description: "Postgres connection. Required for all data operations.",
    docsUrl: "https://supabase.com/docs/guides/database/connecting-to-postgres",
    configured: allSet(["DATABASE_URL"]),
  },
  {
    id: "nextauth",
    name: "NextAuth",
    category: "critical",
    envVars: ["NEXTAUTH_SECRET", "NEXTAUTH_URL"],
    description: "Authentication. Required for all session-gated routes.",
    configured: allSet(["NEXTAUTH_SECRET", "NEXTAUTH_URL"]),
  },
  {
    id: "encryption",
    name: "Encryption Key",
    category: "critical",
    envVars: ["ENCRYPTION_KEY"],
    description: "AES-256-GCM master key. Required for memory encryption.",
    configured: allSet(["ENCRYPTION_KEY"]),
  },
  {
    id: "owner_creds",
    name: "Owner Identity",
    category: "critical",
    envVars: ["VIRGIL_OWNER_EMAIL", "VIRGIL_OWNER_PASSWORD"],
    description: "Owner login credentials.",
    configured: allSet(["VIRGIL_OWNER_EMAIL", "VIRGIL_OWNER_PASSWORD"]),
  },

  // ── LLM PROVIDERS ─────────────────────────────────────────────────────────
  {
    id: "openai",
    name: "OpenAI",
    category: "llm",
    envVars: ["OPENAI_API_KEY"],
    description: "GPT-4o, o1, embeddings.",
    docsUrl: "https://platform.openai.com/api-keys",
    configured: allSet(["OPENAI_API_KEY"]),
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "llm",
    envVars: ["ANTHROPIC_API_KEY"],
    description: "Claude 3.5 Sonnet / Opus.",
    docsUrl: "https://console.anthropic.com/settings/keys",
    configured: allSet(["ANTHROPIC_API_KEY"]),
  },
  {
    id: "google_ai",
    name: "Google Gemini",
    category: "llm",
    envVars: ["GOOGLE_GENERATIVE_AI_API_KEY"],
    description: "Gemini 2.0 Flash / Pro.",
    docsUrl: "https://aistudio.google.com/app/apikey",
    configured: allSet(["GOOGLE_GENERATIVE_AI_API_KEY"]),
  },
  {
    id: "groq",
    name: "Groq",
    category: "llm",
    envVars: ["GROQ_API_KEY"],
    description: "Fast inference (Llama, Mixtral) for low-latency tasks.",
    docsUrl: "https://console.groq.com/keys",
    configured: allSet(["GROQ_API_KEY"]),
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    category: "llm",
    envVars: ["XAI_API_KEY"],
    description: "Grok-2.",
    docsUrl: "https://x.ai/api",
    configured: allSet(["XAI_API_KEY"]),
  },

  // ── VOICE ─────────────────────────────────────────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "voice",
    envVars: ["ELEVENLABS_API_KEY"],
    description: "Text-to-speech synthesis.",
    docsUrl: "https://elevenlabs.io/",
    configured: allSet(["ELEVENLABS_API_KEY"]),
  },
  {
    id: "deepgram",
    name: "Deepgram",
    category: "voice",
    envVars: ["DEEPGRAM_API_KEY"],
    description: "Speech-to-text transcription.",
    docsUrl: "https://console.deepgram.com/",
    configured: allSet(["DEEPGRAM_API_KEY"]),
  },

  // ── CALENDAR & EMAIL ──────────────────────────────────────────────────────
  {
    id: "google_workspace",
    name: "Google Workspace",
    category: "calendar_email",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    description: "Gmail, Google Calendar, Google Drive.",
    docsUrl: "https://console.cloud.google.com/",
    configured: allSet(["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"]),
  },
  {
    id: "microsoft_365",
    name: "Microsoft 365",
    category: "calendar_email",
    envVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET", "MICROSOFT_TENANT_ID"],
    description: "Outlook, Teams, OneDrive.",
    docsUrl: "https://portal.azure.com/",
    configured: allSet(["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET", "MICROSOFT_TENANT_ID"]),
  },

  // ── COMMUNICATION ─────────────────────────────────────────────────────────
  {
    id: "twilio",
    name: "Twilio",
    category: "communication",
    envVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER"],
    description: "SMS and voice calls.",
    docsUrl: "https://console.twilio.com/",
    configured: allSet(["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"]),
  },
  {
    id: "resend",
    name: "Resend",
    category: "communication",
    envVars: ["RESEND_API_KEY"],
    description: "Transactional email.",
    docsUrl: "https://resend.com/api-keys",
    configured: allSet(["RESEND_API_KEY"]),
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "communication",
    envVars: ["SENDGRID_API_KEY"],
    description: "Email marketing and transactional.",
    docsUrl: "https://app.sendgrid.com/settings/api_keys",
    configured: allSet(["SENDGRID_API_KEY"]),
  },
  {
    id: "slack",
    name: "Slack",
    category: "communication",
    envVars: ["SLACK_BOT_TOKEN", "SLACK_SIGNING_SECRET"],
    description: "Slack messaging and notifications.",
    docsUrl: "https://api.slack.com/apps",
    configured: allSet(["SLACK_BOT_TOKEN"]),
  },

  // ── PAYMENTS & FINANCE ────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    category: "payments_finance",
    envVars: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    description: "Payment processing, invoicing, subscriptions.",
    docsUrl: "https://dashboard.stripe.com/apikeys",
    configured: allSet(["STRIPE_SECRET_KEY"]),
  },
  {
    id: "plaid",
    name: "Plaid",
    category: "payments_finance",
    envVars: ["PLAID_CLIENT_ID", "PLAID_SECRET"],
    description: "Bank account linking, transaction data.",
    docsUrl: "https://dashboard.plaid.com/developers/keys",
    configured: allSet(["PLAID_CLIENT_ID", "PLAID_SECRET"]),
  },

  // ── STORAGE ───────────────────────────────────────────────────────────────
  {
    id: "supabase_storage",
    name: "Supabase Storage",
    category: "storage",
    envVars: ["SUPABASE_SERVICE_ROLE_KEY"],
    description: "File storage, private buckets.",
    configured: allSet(["SUPABASE_SERVICE_ROLE_KEY"]),
  },
  {
    id: "aws_s3",
    name: "AWS S3",
    category: "storage",
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_S3_BUCKET"],
    description: "Object storage, backups.",
    docsUrl: "https://console.aws.amazon.com/iam/",
    configured: allSet(["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]),
  },
  {
    id: "cloudflare_r2",
    name: "Cloudflare R2",
    category: "storage",
    envVars: ["CLOUDFLARE_R2_ACCESS_KEY", "CLOUDFLARE_R2_SECRET_KEY", "CLOUDFLARE_R2_BUCKET"],
    description: "S3-compatible object storage, zero egress.",
    docsUrl: "https://dash.cloudflare.com/r2",
    configured: allSet(["CLOUDFLARE_R2_ACCESS_KEY", "CLOUDFLARE_R2_SECRET_KEY"]),
  },

  // ── SEARCH & KNOWLEDGE ────────────────────────────────────────────────────
  {
    id: "perplexity",
    name: "Perplexity",
    category: "search",
    envVars: ["PERPLEXITY_API_KEY"],
    description: "Real-time web search and research.",
    docsUrl: "https://docs.perplexity.ai/",
    configured: allSet(["PERPLEXITY_API_KEY"]),
  },
  {
    id: "tavily",
    name: "Tavily",
    category: "search",
    envVars: ["TAVILY_API_KEY"],
    description: "AI-optimized web search for agents.",
    docsUrl: "https://tavily.com/",
    configured: allSet(["TAVILY_API_KEY"]),
  },
  {
    id: "exa",
    name: "Exa",
    category: "search",
    envVars: ["EXA_API_KEY"],
    description: "Semantic web search.",
    docsUrl: "https://exa.ai/",
    configured: allSet(["EXA_API_KEY"]),
  },
  {
    id: "serper",
    name: "Serper",
    category: "search",
    envVars: ["SERPER_API_KEY"],
    description: "Google search results API.",
    docsUrl: "https://serper.dev/",
    configured: allSet(["SERPER_API_KEY"]),
  },

  // ── CODE & DEV TOOLS ──────────────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    category: "code_dev",
    envVars: ["GITHUB_APP_ID", "GITHUB_APP_PRIVATE_KEY", "GITHUB_INSTALLATION_ID"],
    description: "Repos, PRs, issues, code review.",
    docsUrl: "https://github.com/settings/apps",
    configured: allSet(["GITHUB_APP_ID", "GITHUB_APP_PRIVATE_KEY"]),
  },
  {
    id: "linear",
    name: "Linear",
    category: "code_dev",
    envVars: ["LINEAR_API_KEY"],
    description: "Project and issue tracking.",
    docsUrl: "https://linear.app/settings/api",
    configured: allSet(["LINEAR_API_KEY"]),
  },
  {
    id: "notion",
    name: "Notion",
    category: "code_dev",
    envVars: ["NOTION_API_KEY"],
    description: "Docs, databases, wikis.",
    docsUrl: "https://www.notion.so/my-integrations",
    configured: allSet(["NOTION_API_KEY"]),
  },

  // ── CRM & BUSINESS ────────────────────────────────────────────────────────
  {
    id: "airtable",
    name: "Airtable",
    category: "crm_business",
    envVars: ["AIRTABLE_API_KEY", "AIRTABLE_BASE_ID"],
    description: "Flexible database / CRM.",
    docsUrl: "https://airtable.com/account",
    configured: allSet(["AIRTABLE_API_KEY"]),
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "crm_business",
    envVars: ["HUBSPOT_API_KEY"],
    description: "CRM, deals, contacts, marketing.",
    docsUrl: "https://app.hubspot.com/profile-preferences/integrations",
    configured: allSet(["HUBSPOT_API_KEY"]),
  },

  // ── MAPS & TRAVEL ─────────────────────────────────────────────────────────
  {
    id: "google_maps",
    name: "Google Maps",
    category: "maps_travel",
    envVars: ["GOOGLE_MAPS_API_KEY"],
    description: "Geocoding, directions, places.",
    docsUrl: "https://console.cloud.google.com/",
    configured: allSet(["GOOGLE_MAPS_API_KEY"]),
  },
  {
    id: "amadeus",
    name: "Amadeus",
    category: "maps_travel",
    envVars: ["AMADEUS_API_KEY", "AMADEUS_API_SECRET"],
    description: "Flight and hotel search.",
    docsUrl: "https://developers.amadeus.com/",
    configured: allSet(["AMADEUS_API_KEY", "AMADEUS_API_SECRET"]),
  },

  // ── REAL ESTATE ───────────────────────────────────────────────────────────
  {
    id: "attom",
    name: "ATTOM",
    category: "real_estate",
    envVars: ["ATTOM_API_KEY"],
    description: "Property data, valuations, ownership.",
    docsUrl: "https://api.attomdata.com/",
    configured: allSet(["ATTOM_API_KEY"]),
  },

  // ── TRADING & FINANCIAL DATA ──────────────────────────────────────────────
  {
    id: "alpaca",
    name: "Alpaca",
    category: "trading_finance",
    envVars: ["ALPACA_API_KEY", "ALPACA_API_SECRET"],
    description: "Stock trading, paper and live.",
    docsUrl: "https://app.alpaca.markets/paper/dashboard/overview",
    configured: allSet(["ALPACA_API_KEY", "ALPACA_API_SECRET"]),
  },
  {
    id: "polygon",
    name: "Polygon.io",
    category: "trading_finance",
    envVars: ["POLYGON_API_KEY"],
    description: "Real-time and historical market data.",
    docsUrl: "https://polygon.io/dashboard/api-keys",
    configured: allSet(["POLYGON_API_KEY"]),
  },
  {
    id: "alpha_vantage",
    name: "Alpha Vantage",
    category: "trading_finance",
    envVars: ["ALPHA_VANTAGE_API_KEY"],
    description: "Stock, forex, crypto data.",
    docsUrl: "https://www.alphavantage.co/support/#api-key",
    configured: allSet(["ALPHA_VANTAGE_API_KEY"]),
  },
  {
    id: "coinbase",
    name: "Coinbase Advanced",
    category: "trading_finance",
    envVars: ["COINBASE_API_KEY", "COINBASE_API_SECRET"],
    description: "Crypto trading and portfolio.",
    docsUrl: "https://www.coinbase.com/settings/api",
    configured: allSet(["COINBASE_API_KEY", "COINBASE_API_SECRET"]),
  },

  // ── MONITORING & SECURITY ─────────────────────────────────────────────────
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring_security",
    envVars: ["SENTRY_DSN"],
    description: "Error tracking and performance monitoring.",
    docsUrl: "https://sentry.io/settings/",
    configured: allSet(["SENTRY_DSN"]),
  },
  {
    id: "upstash_redis",
    name: "Upstash Redis",
    category: "monitoring_security",
    envVars: ["UPSTASH_REDIS_URL", "UPSTASH_REDIS_TOKEN"],
    description: "Rate limiting, caching, session storage.",
    docsUrl: "https://console.upstash.com/",
    configured: allSet(["UPSTASH_REDIS_URL", "UPSTASH_REDIS_TOKEN"]),
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "monitoring_security",
    envVars: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ZONE_ID"],
    description: "DNS, WAF, CDN, access rules.",
    docsUrl: "https://dash.cloudflare.com/profile/api-tokens",
    configured: allSet(["CLOUDFLARE_API_TOKEN"]),
  },

  // ── FOOD DELIVERY & RESTAURANT RESERVATIONS ───────────────────────────────
  {
    id: "ifood",
    name: "iFood",
    category: "food_delivery",
    envVars: ["IFOOD_CLIENT_ID", "IFOOD_CLIENT_SECRET"],
    description: "Food delivery in Brazil. Order for Sir and prepare safe meals for Ms. Barbosa. Stage first; never auto-execute.",
    docsUrl: "https://developer.ifood.com.br/",
    configured: allSet(["IFOOD_CLIENT_ID", "IFOOD_CLIENT_SECRET"]),
  },
  {
    id: "rappi",
    name: "Rappi",
    category: "food_delivery",
    envVars: ["RAPPI_API_KEY"],
    description: "Food, groceries, pharmacy, errands across LATAM.",
    docsUrl: "https://dev.rappi.com/",
    configured: allSet(["RAPPI_API_KEY"]),
  },
  {
    id: "uber_eats",
    name: "Uber Eats",
    category: "food_delivery",
    envVars: ["UBER_EATS_CLIENT_ID", "UBER_EATS_CLIENT_SECRET"],
    description: "Food delivery globally where available.",
    docsUrl: "https://developer.uber.com/docs/eats",
    configured: allSet(["UBER_EATS_CLIENT_ID", "UBER_EATS_CLIENT_SECRET"]),
  },
  {
    id: "doordash",
    name: "DoorDash",
    category: "food_delivery",
    envVars: ["DOORDASH_DEVELOPER_ID", "DOORDASH_KEY_ID", "DOORDASH_SIGNING_SECRET"],
    description: "Food and grocery delivery (US).",
    docsUrl: "https://developer.doordash.com/en-US/docs/drive/reference/jwt/",
    configured: allSet(["DOORDASH_DEVELOPER_ID", "DOORDASH_KEY_ID"]),
  },
  {
    id: "instacart",
    name: "Instacart",
    category: "food_delivery",
    envVars: ["INSTACART_API_KEY"],
    description: "Grocery delivery (US).",
    docsUrl: "https://docs.instacart.com/",
    configured: allSet(["INSTACART_API_KEY"]),
  },
  {
    id: "ze_delivery",
    name: "Zé Delivery",
    category: "food_delivery",
    envVars: ["ZE_DELIVERY_API_KEY"],
    description: "Alcohol delivery in Brazil. Execute with owner approval only.",
    configured: allSet(["ZE_DELIVERY_API_KEY"]),
  },
  {
    id: "opentable",
    name: "OpenTable",
    category: "food_delivery",
    envVars: ["OPENTABLE_CLIENT_ID", "OPENTABLE_CLIENT_SECRET"],
    description: "Restaurant reservations globally.",
    docsUrl: "https://developer.opentable.com/",
    configured: allSet(["OPENTABLE_CLIENT_ID", "OPENTABLE_CLIENT_SECRET"]),
  },
  {
    id: "resy",
    name: "Resy",
    category: "food_delivery",
    envVars: ["RESY_API_KEY"],
    description: "High-end restaurant reservations (US).",
    docsUrl: "https://resy.com/",
    configured: allSet(["RESY_API_KEY"]),
  },
  {
    id: "thefork",
    name: "TheFork",
    category: "food_delivery",
    envVars: ["THEFORK_API_KEY"],
    description: "Restaurant booking across Europe and Brazil.",
    docsUrl: "https://www.thefork.com/",
    configured: allSet(["THEFORK_API_KEY"]),
  },
  {
    id: "sevenrooms",
    name: "SevenRooms",
    category: "food_delivery",
    envVars: ["SEVENROOMS_CLIENT_ID", "SEVENROOMS_CLIENT_SECRET"],
    description: "Hospitality CRM and table reservations.",
    docsUrl: "https://sevenrooms.com/",
    configured: allSet(["SEVENROOMS_CLIENT_ID", "SEVENROOMS_CLIENT_SECRET"]),
  },

  // ── BRAZIL DAILY LIFE ─────────────────────────────────────────────────────
  {
    id: "brasil_api",
    name: "BrasilAPI",
    category: "brazil_ops",
    envVars: ["BRASIL_API_KEY"],
    description: "CEP lookup, CNPJ validation, bank codes, holidays. Key optional for public endpoints.",
    docsUrl: "https://brasilapi.com.br/docs",
    configured: true, // public endpoints require no key
  },
  {
    id: "viacep",
    name: "ViaCEP",
    category: "brazil_ops",
    envVars: [],
    description: "Brazilian address lookup by postal code. Free public API.",
    docsUrl: "https://viacep.com.br/",
    configured: true,
  },
  {
    id: "correios",
    name: "Correios Tracking",
    category: "brazil_ops",
    envVars: ["CORREIOS_USER", "CORREIOS_ACCESS_CODE"],
    description: "Package tracking via Brazilian postal service.",
    docsUrl: "https://www.correios.com.br/atendimento/developers",
    configured: allSet(["CORREIOS_USER", "CORREIOS_ACCESS_CODE"]),
  },
  {
    id: "bcb_ptax",
    name: "Banco Central PTAX",
    category: "brazil_ops",
    envVars: [],
    description: "Official USD/BRL exchange rates from Banco Central do Brasil. Free public API.",
    docsUrl: "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/documentacao",
    configured: true,
  },
  {
    id: "ride99",
    name: "99",
    category: "brazil_ops",
    envVars: ["RIDE99_API_KEY"],
    description: "Ride-hailing in Brazil — primary Uber alternative.",
    docsUrl: "https://99app.com/",
    configured: allSet(["RIDE99_API_KEY"]),
  },
  {
    id: "cabify",
    name: "Cabify",
    category: "brazil_ops",
    envVars: ["CABIFY_API_KEY"],
    description: "Ride-hailing where available.",
    docsUrl: "https://cabify.com/",
    configured: allSet(["CABIFY_API_KEY"]),
  },
  {
    id: "loggi",
    name: "Loggi",
    category: "brazil_ops",
    envVars: ["LOGGI_API_KEY"],
    description: "Same-day courier and logistics in Brazil.",
    docsUrl: "https://docs.loggi.com/",
    configured: allSet(["LOGGI_API_KEY"]),
  },
  {
    id: "lalamove",
    name: "Lalamove",
    category: "brazil_ops",
    envVars: ["LALAMOVE_API_KEY", "LALAMOVE_API_SECRET"],
    description: "On-demand errands and courier delivery.",
    docsUrl: "https://developers.lalamove.com/",
    configured: allSet(["LALAMOVE_API_KEY", "LALAMOVE_API_SECRET"]),
  },
  {
    id: "melhor_envio",
    name: "Melhor Envio",
    category: "brazil_ops",
    envVars: ["MELHOR_ENVIO_API_KEY"],
    description: "Shipping quotes and labels for Brazil.",
    docsUrl: "https://docs.melhorenvio.com.br/",
    configured: allSet(["MELHOR_ENVIO_API_KEY"]),
  },
  {
    id: "clicksign",
    name: "Clicksign",
    category: "brazil_ops",
    envVars: ["CLICKSIGN_API_KEY"],
    description: "Brazilian e-signature platform.",
    docsUrl: "https://developers.clicksign.com/",
    configured: allSet(["CLICKSIGN_API_KEY"]),
  },
  {
    id: "mercado_livre",
    name: "Mercado Livre",
    category: "brazil_ops",
    envVars: ["MERCADO_LIVRE_APP_ID", "MERCADO_LIVRE_SECRET"],
    description: "Brazil/LATAM marketplace — shopping, selling, logistics.",
    docsUrl: "https://developers.mercadolivre.com.br/",
    configured: allSet(["MERCADO_LIVRE_APP_ID", "MERCADO_LIVRE_SECRET"]),
  },

  // ── HOUSEHOLD CONCIERGE ───────────────────────────────────────────────────
  {
    id: "taskrabbit",
    name: "TaskRabbit",
    category: "concierge",
    envVars: ["TASKRABBIT_API_KEY"],
    description: "Errands, handyman, furniture assembly.",
    docsUrl: "https://developers.taskrabbit.com/",
    configured: allSet(["TASKRABBIT_API_KEY"]),
  },
  {
    id: "thumbtack",
    name: "Thumbtack",
    category: "concierge",
    envVars: ["THUMBTACK_API_KEY"],
    description: "Local contractors and home services.",
    docsUrl: "https://www.thumbtack.com/partners/",
    configured: allSet(["THUMBTACK_API_KEY"]),
  },
  {
    id: "getninjas",
    name: "GetNinjas",
    category: "concierge",
    envVars: ["GETNINJAS_API_KEY"],
    description: "Home services marketplace in Brazil.",
    configured: allSet(["GETNINJAS_API_KEY"]),
  },
  {
    id: "parafuzo",
    name: "Parafuzo",
    category: "concierge",
    envVars: ["PARAFUZO_API_KEY"],
    description: "Cleaning and home services in Brazil.",
    configured: allSet(["PARAFUZO_API_KEY"]),
  },

  // ── SHOPPING & PRICE INTELLIGENCE ────────────────────────────────────────
  {
    id: "amazon_pa",
    name: "Amazon Product Advertising",
    category: "shopping_procurement",
    envVars: ["AMAZON_PA_ACCESS_KEY", "AMAZON_PA_SECRET_KEY", "AMAZON_PA_ASSOCIATE_TAG"],
    description: "Product search, pricing, availability.",
    docsUrl: "https://webservices.amazon.com/paapi5/documentation/",
    configured: allSet(["AMAZON_PA_ACCESS_KEY", "AMAZON_PA_SECRET_KEY"]),
  },
  {
    id: "ebay",
    name: "eBay",
    category: "shopping_procurement",
    envVars: ["EBAY_APP_ID", "EBAY_CERT_ID"],
    description: "Cars, parts, collectibles, used goods.",
    docsUrl: "https://developer.ebay.com/",
    configured: allSet(["EBAY_APP_ID", "EBAY_CERT_ID"]),
  },
  {
    id: "keepa",
    name: "Keepa",
    category: "shopping_procurement",
    envVars: ["KEEPA_API_KEY"],
    description: "Amazon price history and deal tracking.",
    docsUrl: "https://keepa.com/#!api",
    configured: allSet(["KEEPA_API_KEY"]),
  },
  {
    id: "google_shopping",
    name: "Google Shopping (SerpAPI)",
    category: "shopping_procurement",
    envVars: ["SERPAPI_API_KEY"],
    description: "Price comparisons across retailers.",
    docsUrl: "https://serpapi.com/",
    configured: allSet(["SERPAPI_API_KEY"]),
  },
  {
    id: "kabum",
    name: "Kabum",
    category: "shopping_procurement",
    envVars: ["KABUM_API_KEY"],
    description: "Brazil tech and electronics retail.",
    docsUrl: "https://www.kabum.com.br/",
    configured: allSet(["KABUM_API_KEY"]),
  },
  {
    id: "magalu",
    name: "Magalu",
    category: "shopping_procurement",
    envVars: ["MAGALU_CLIENT_ID", "MAGALU_CLIENT_SECRET"],
    description: "Brazil retail — Magazine Luiza marketplace.",
    docsUrl: "https://developers.magazineluiza.com.br/",
    configured: allSet(["MAGALU_CLIENT_ID", "MAGALU_CLIENT_SECRET"]),
  },

  // ── CARS & AUTOMOTIVE ─────────────────────────────────────────────────────
  {
    id: "nhtsa",
    name: "NHTSA VIN API",
    category: "automotive",
    envVars: [],
    description: "VIN decoding, safety recalls, manufacturer data. Free public API.",
    docsUrl: "https://vpic.nhtsa.dot.gov/api/",
    configured: true,
  },
  {
    id: "cargurus",
    name: "CarGurus",
    category: "automotive",
    envVars: ["CARGURUS_API_KEY"],
    description: "Car pricing intelligence and market analysis.",
    docsUrl: "https://www.cargurus.com/Cars/api/",
    configured: allSet(["CARGURUS_API_KEY"]),
  },
  {
    id: "bat",
    name: "Bring a Trailer",
    category: "automotive",
    envVars: ["BAT_API_KEY"],
    description: "Enthusiast car auction tracking.",
    docsUrl: "https://bringatrailer.com/",
    configured: allSet(["BAT_API_KEY"]),
  },
  {
    id: "hagerty",
    name: "Hagerty Valuation",
    category: "automotive",
    envVars: ["HAGERTY_API_KEY"],
    description: "Collector and classic car valuations.",
    docsUrl: "https://www.hagerty.com/valuationtools",
    configured: allSet(["HAGERTY_API_KEY"]),
  },
  {
    id: "rockauto",
    name: "RockAuto",
    category: "automotive",
    envVars: ["ROCKAUTO_AFFILIATE_KEY"],
    description: "Parts lookup and pricing across makes and models.",
    docsUrl: "https://www.rockauto.com/",
    configured: allSet(["ROCKAUTO_AFFILIATE_KEY"]),
  },
  {
    id: "carfax",
    name: "Carfax",
    category: "automotive",
    envVars: ["CARFAX_API_KEY"],
    description: "Vehicle history reports.",
    docsUrl: "https://www.carfax.com/",
    configured: allSet(["CARFAX_API_KEY"]),
  },

  // ── PRIVATE AVIATION ──────────────────────────────────────────────────────
  {
    id: "avinode",
    name: "Avinode",
    category: "private_aviation",
    envVars: ["AVINODE_API_KEY"],
    description: "Private jet marketplace — charter pricing and availability.",
    docsUrl: "https://www.avinode.com/",
    configured: allSet(["AVINODE_API_KEY"]),
  },
  {
    id: "victor",
    name: "Victor",
    category: "private_aviation",
    envVars: ["VICTOR_API_KEY"],
    description: "On-demand private jet charter quotes.",
    docsUrl: "https://www.victor.aero/",
    configured: allSet(["VICTOR_API_KEY"]),
  },
  {
    id: "privatefly",
    name: "PrivateFly",
    category: "private_aviation",
    envVars: ["PRIVATEFLY_API_KEY"],
    description: "Charter quotes and jet comparison.",
    docsUrl: "https://www.privatefly.com/",
    configured: allSet(["PRIVATEFLY_API_KEY"]),
  },
  {
    id: "foreflight",
    name: "ForeFlight",
    category: "private_aviation",
    envVars: ["FOREFLIGHT_API_KEY"],
    description: "Aviation planning — weather, NOTAMs, performance.",
    docsUrl: "https://www.foreflight.com/",
    configured: allSet(["FOREFLIGHT_API_KEY"]),
  },
  {
    id: "flightradar24",
    name: "FlightRadar24",
    category: "private_aviation",
    envVars: ["FLIGHTRADAR24_API_KEY"],
    description: "Live flight tracking.",
    docsUrl: "https://www.flightradar24.com/blog/flight-radar24-api/",
    configured: allSet(["FLIGHTRADAR24_API_KEY"]),
  },
  {
    id: "adsb_exchange",
    name: "ADS-B Exchange",
    category: "private_aviation",
    envVars: ["ADSB_EXCHANGE_API_KEY"],
    description: "Unfiltered aircraft tracking data.",
    docsUrl: "https://www.adsbexchange.com/data/",
    configured: allSet(["ADSB_EXCHANGE_API_KEY"]),
  },

  // ── HOTELS, LUXURY & EVENTS ───────────────────────────────────────────────
  {
    id: "booking_com",
    name: "Booking.com",
    category: "hotels_events",
    envVars: ["BOOKING_API_KEY"],
    description: "Hotel search and reservations.",
    docsUrl: "https://developers.booking.com/",
    configured: allSet(["BOOKING_API_KEY"]),
  },
  {
    id: "expedia_rapid",
    name: "Expedia Rapid",
    category: "hotels_events",
    envVars: ["EXPEDIA_API_KEY", "EXPEDIA_API_SECRET"],
    description: "Hotel and travel inventory.",
    docsUrl: "https://developers.expediagroup.com/docs/products/rapid",
    configured: allSet(["EXPEDIA_API_KEY", "EXPEDIA_API_SECRET"]),
  },
  {
    id: "ticketmaster",
    name: "Ticketmaster",
    category: "hotels_events",
    envVars: ["TICKETMASTER_API_KEY"],
    description: "Events, concerts, sports tickets.",
    docsUrl: "https://developer.ticketmaster.com/",
    configured: allSet(["TICKETMASTER_API_KEY"]),
  },
  {
    id: "stubhub",
    name: "StubHub",
    category: "hotels_events",
    envVars: ["STUBHUB_APP_TOKEN"],
    description: "Secondary market tickets.",
    docsUrl: "https://developer.viagogo.net/",
    configured: allSet(["STUBHUB_APP_TOKEN"]),
  },
  {
    id: "seatgeek",
    name: "SeatGeek",
    category: "hotels_events",
    envVars: ["SEATGEEK_CLIENT_ID", "SEATGEEK_CLIENT_SECRET"],
    description: "Ticket search with deal score.",
    docsUrl: "https://platform.seatgeek.com/",
    configured: allSet(["SEATGEEK_CLIENT_ID", "SEATGEEK_CLIENT_SECRET"]),
  },
  {
    id: "sympla",
    name: "Sympla",
    category: "hotels_events",
    envVars: ["SYMPLA_API_KEY"],
    description: "Brazil events platform.",
    docsUrl: "https://developers.sympla.com.br/",
    configured: allSet(["SYMPLA_API_KEY"]),
  },
  {
    id: "ingresse",
    name: "Ingresse",
    category: "hotels_events",
    envVars: ["INGRESSE_API_KEY"],
    description: "Brazil ticket sales and events.",
    docsUrl: "https://docs.ingresse.com/",
    configured: allSet(["INGRESSE_API_KEY"]),
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    category: "hotels_events",
    envVars: ["EVENTBRITE_PRIVATE_TOKEN"],
    description: "Event discovery and ticketing.",
    docsUrl: "https://www.eventbrite.com/platform/api",
    configured: allSet(["EVENTBRITE_PRIVATE_TOKEN"]),
  },

  // ── NEWS & INTELLIGENCE ────────────────────────────────────────────────────
  {
    id: "newsapi",
    name: "NewsAPI",
    category: "news_intelligence",
    envVars: ["NEWSAPI_API_KEY"],
    description: "News monitoring from 80,000+ sources.",
    docsUrl: "https://newsapi.org/",
    configured: allSet(["NEWSAPI_API_KEY"]),
  },
  {
    id: "brave_search",
    name: "Brave Search",
    category: "news_intelligence",
    envVars: ["BRAVE_SEARCH_API_KEY"],
    description: "Independent web search — no Google dependency.",
    docsUrl: "https://api.search.brave.com/",
    configured: allSet(["BRAVE_SEARCH_API_KEY"]),
  },
  {
    id: "diffbot",
    name: "Diffbot",
    category: "news_intelligence",
    envVars: ["DIFFBOT_TOKEN"],
    description: "Web entity and article extraction.",
    docsUrl: "https://www.diffbot.com/dev/docs/",
    configured: allSet(["DIFFBOT_TOKEN"]),
  },
  {
    id: "crunchbase",
    name: "Crunchbase",
    category: "news_intelligence",
    envVars: ["CRUNCHBASE_API_KEY"],
    description: "Company research, funding, investor data.",
    docsUrl: "https://data.crunchbase.com/docs",
    configured: allSet(["CRUNCHBASE_API_KEY"]),
  },
  {
    id: "apollo",
    name: "Apollo.io",
    category: "news_intelligence",
    envVars: ["APOLLO_API_KEY"],
    description: "Sales intelligence and contact/company data.",
    docsUrl: "https://apolloio.github.io/apollo-api-docs/",
    configured: allSet(["APOLLO_API_KEY"]),
  },
  {
    id: "clearbit",
    name: "Clearbit",
    category: "news_intelligence",
    envVars: ["CLEARBIT_API_KEY"],
    description: "Company and contact enrichment.",
    docsUrl: "https://dashboard.clearbit.com/docs",
    configured: allSet(["CLEARBIT_API_KEY"]),
  },
  {
    id: "similarweb",
    name: "Similarweb",
    category: "news_intelligence",
    envVars: ["SIMILARWEB_API_KEY"],
    description: "Competitor traffic and digital intelligence.",
    docsUrl: "https://developers.similarweb.com/",
    configured: allSet(["SIMILARWEB_API_KEY"]),
  },
  {
    id: "gdelt",
    name: "GDELT",
    category: "news_intelligence",
    envVars: [],
    description: "Global events and news intelligence — free public dataset.",
    docsUrl: "https://www.gdeltproject.org/data.html",
    configured: true,
  },

  // ── PERSONAL SAFETY & LOCATION ───────────────────────────────────────────
  {
    id: "noonlight",
    name: "Noonlight",
    category: "safety_location",
    envVars: ["NOONLIGHT_TOKEN"],
    description: "Safety workflows and emergency dispatch. Consent-driven.",
    docsUrl: "https://docs.noonlight.com/",
    configured: allSet(["NOONLIGHT_TOKEN"]),
  },
  {
    id: "what3words",
    name: "what3words",
    category: "safety_location",
    envVars: ["WHAT3WORDS_API_KEY"],
    description: "Precise location with three-word addresses.",
    docsUrl: "https://developer.what3words.com/",
    configured: allSet(["WHAT3WORDS_API_KEY"]),
  },

  // ── MEDICAL, PHARMACY & HEALTH APPOINTMENTS ──────────────────────────────
  {
    id: "zocdoc",
    name: "Zocdoc",
    category: "medical_pharmacy",
    envVars: ["ZOCDOC_API_KEY"],
    description: "Doctor appointment search and booking.",
    docsUrl: "https://www.zocdoc.com/wl/api",
    configured: allSet(["ZOCDOC_API_KEY"]),
  },
  {
    id: "doctoralia",
    name: "Doctoralia",
    category: "medical_pharmacy",
    envVars: ["DOCTORALIA_API_KEY"],
    description: "Doctor search and appointment booking in Brazil.",
    docsUrl: "https://www.doctoralia.com.br/",
    configured: allSet(["DOCTORALIA_API_KEY"]),
  },
  {
    id: "goodrx",
    name: "GoodRx",
    category: "medical_pharmacy",
    envVars: ["GOODRX_API_KEY", "GOODRX_API_SECRET"],
    description: "Medication pricing and pharmacy coupons.",
    docsUrl: "https://www.goodrx.com/developer",
    configured: allSet(["GOODRX_API_KEY", "GOODRX_API_SECRET"]),
  },

  // ── BRAZIL BUSINESS / PAYMENTS / ERP ─────────────────────────────────────
  {
    id: "asaas",
    name: "Asaas",
    category: "brazil_business",
    envVars: ["ASAAS_API_KEY"],
    description: "Brazil billing, Pix, boleto, recurring charges.",
    docsUrl: "https://docs.asaas.com/",
    configured: allSet(["ASAAS_API_KEY"]),
  },
  {
    id: "efi",
    name: "Efí (Gerencianet)",
    category: "brazil_business",
    envVars: ["EFI_CLIENT_ID", "EFI_CLIENT_SECRET"],
    description: "Pix, boleto, payment links in Brazil.",
    docsUrl: "https://dev.efipay.com.br/",
    configured: allSet(["EFI_CLIENT_ID", "EFI_CLIENT_SECRET"]),
  },
  {
    id: "pagarme",
    name: "Pagar.me",
    category: "brazil_business",
    envVars: ["PAGARME_API_KEY"],
    description: "Brazil payments — cards, boleto, Pix.",
    docsUrl: "https://docs.pagar.me/",
    configured: allSet(["PAGARME_API_KEY"]),
  },
  {
    id: "mercado_pago",
    name: "Mercado Pago",
    category: "brazil_business",
    envVars: ["MERCADO_PAGO_ACCESS_TOKEN"],
    description: "Payments across Brazil and LATAM.",
    docsUrl: "https://www.mercadopago.com.br/developers/",
    configured: allSet(["MERCADO_PAGO_ACCESS_TOKEN"]),
  },
  {
    id: "nfeio",
    name: "NFe.io",
    category: "brazil_business",
    envVars: ["NFEIO_API_KEY"],
    description: "Nota fiscal (NF-e, NFS-e) issuance.",
    docsUrl: "https://nfe.io/docs/",
    configured: allSet(["NFEIO_API_KEY"]),
  },
  {
    id: "omie",
    name: "Omie",
    category: "brazil_business",
    envVars: ["OMIE_APP_KEY", "OMIE_APP_SECRET"],
    description: "ERP and accounting for Brazil SMBs.",
    docsUrl: "https://developer.omie.com.br/",
    configured: allSet(["OMIE_APP_KEY", "OMIE_APP_SECRET"]),
  },
  {
    id: "conta_azul",
    name: "Conta Azul",
    category: "brazil_business",
    envVars: ["CONTA_AZUL_CLIENT_ID", "CONTA_AZUL_CLIENT_SECRET"],
    description: "SMB accounting and invoicing in Brazil.",
    docsUrl: "https://developers.contaazul.com/",
    configured: allSet(["CONTA_AZUL_CLIENT_ID", "CONTA_AZUL_CLIENT_SECRET"]),
  },
  {
    id: "nuvemshop",
    name: "Nuvemshop",
    category: "brazil_business",
    envVars: ["NUVEMSHOP_ACCESS_TOKEN", "NUVEMSHOP_USER_ID"],
    description: "Brazil e-commerce platform API.",
    docsUrl: "https://tiendanube.github.io/api-documentation/",
    configured: allSet(["NUVEMSHOP_ACCESS_TOKEN", "NUVEMSHOP_USER_ID"]),
  },

  // ── DEV INFRA (EXPANDED) ─────────────────────────────────────────────────
  {
    id: "gitlab",
    name: "GitLab",
    category: "dev_infra",
    envVars: ["GITLAB_TOKEN"],
    description: "Repos, CI/CD pipelines, issues.",
    docsUrl: "https://docs.gitlab.com/ee/api/",
    configured: allSet(["GITLAB_TOKEN"]),
  },
  {
    id: "railway",
    name: "Railway",
    category: "dev_infra",
    envVars: ["RAILWAY_TOKEN"],
    description: "App deployments and database provisioning.",
    docsUrl: "https://docs.railway.app/reference/public-api",
    configured: allSet(["RAILWAY_TOKEN"]),
  },
  {
    id: "render",
    name: "Render",
    category: "dev_infra",
    envVars: ["RENDER_API_KEY"],
    description: "Cloud deployments.",
    docsUrl: "https://render.com/docs/api",
    configured: allSet(["RENDER_API_KEY"]),
  },
  {
    id: "flyio",
    name: "Fly.io",
    category: "dev_infra",
    envVars: ["FLY_API_TOKEN"],
    description: "Edge deployments and app hosting.",
    docsUrl: "https://fly.io/docs/machines/api/",
    configured: allSet(["FLY_API_TOKEN"]),
  },
  {
    id: "neon",
    name: "Neon",
    category: "dev_infra",
    envVars: ["NEON_API_KEY"],
    description: "Serverless Postgres database management.",
    docsUrl: "https://api-docs.neon.tech/",
    configured: allSet(["NEON_API_KEY"]),
  },
  {
    id: "launchdarkly",
    name: "LaunchDarkly",
    category: "dev_infra",
    envVars: ["LAUNCHDARKLY_SDK_KEY"],
    description: "Feature flags and controlled rollouts.",
    docsUrl: "https://docs.launchdarkly.com/",
    configured: allSet(["LAUNCHDARKLY_SDK_KEY"]),
  },
  {
    id: "better_stack",
    name: "Better Stack",
    category: "dev_infra",
    envVars: ["BETTER_STACK_SOURCE_TOKEN"],
    description: "Logs, uptime monitoring, on-call.",
    docsUrl: "https://betterstack.com/docs/",
    configured: allSet(["BETTER_STACK_SOURCE_TOKEN"]),
  },
  {
    id: "grafana_cloud",
    name: "Grafana Cloud",
    category: "dev_infra",
    envVars: ["GRAFANA_API_KEY", "GRAFANA_INSTANCE_ID"],
    description: "Metrics, dashboards, alerting.",
    docsUrl: "https://grafana.com/docs/grafana-cloud/",
    configured: allSet(["GRAFANA_API_KEY", "GRAFANA_INSTANCE_ID"]),
  },
  {
    id: "loops",
    name: "Loops",
    category: "dev_infra",
    envVars: ["LOOPS_API_KEY"],
    description: "Product and lifecycle email automation.",
    docsUrl: "https://loops.so/docs",
    configured: allSet(["LOOPS_API_KEY"]),
  },
];

export const CATEGORY_LABELS: Record<ConnectorCategory, string> = {
  critical:             "Critical — App Will Not Start Without These",
  llm:                  "LLM Providers",
  voice:                "Voice (TTS / STT)",
  calendar_email:       "Calendar & Email",
  communication:        "Communication",
  payments_finance:     "Payments & Finance",
  storage:              "Storage",
  search:               "Search & Knowledge",
  code_dev:             "Code & Developer Tools",
  crm_business:         "CRM & Business",
  maps_travel:          "Maps & Travel",
  real_estate:          "Real Estate",
  trading_finance:      "Trading & Financial Data",
  monitoring_security:  "Monitoring & Security",
  // Real-World Command Layer
  food_delivery:        "Food Delivery & Restaurant Reservations",
  brazil_ops:           "Brazil Daily Life",
  concierge:            "Household Concierge & Local Services",
  shopping_procurement: "Shopping & Price Intelligence",
  automotive:           "Cars, Parts & Automotive",
  private_aviation:     "Private Aviation",
  hotels_events:        "Hotels, Luxury & Events",
  news_intelligence:    "News, Intelligence & Research",
  safety_location:      "Personal Safety & Location",
  medical_pharmacy:     "Medical, Pharmacy & Health",
  brazil_business:      "Brazil Business, Payments & ERP",
  dev_infra:            "Developer Infrastructure (Expanded)",
};

export const CATEGORY_ORDER: ConnectorCategory[] = [
  "critical",
  "llm",
  "voice",
  "calendar_email",
  "communication",
  "payments_finance",
  "storage",
  "search",
  "code_dev",
  "crm_business",
  "maps_travel",
  "real_estate",
  "trading_finance",
  "monitoring_security",
  "food_delivery",
  "brazil_ops",
  "concierge",
  "shopping_procurement",
  "automotive",
  "private_aviation",
  "hotels_events",
  "news_intelligence",
  "safety_location",
  "medical_pharmacy",
  "brazil_business",
  "dev_infra",
];
